export { default as DataLakeStorageGen1Icon } from './azure/Microsoft.Analytics/DataLakeStorageGen1Icon'
export { default as DatabricksIcon } from './azure/Microsoft.Analytics/DatabricksIcon'
export { default as EventHubClusterIcon } from './azure/Microsoft.Analytics/EventHubClusterIcon'
export { default as EventHubIcon } from './azure/Microsoft.Analytics/EventHubIcon'
export { default as HDInsightClusterIcon } from './azure/Microsoft.Analytics/HDInsightClusterIcon'
export { default as LogAnalyticsWorkspaceIcon } from './azure/Microsoft.Analytics/LogAnalyticsWorkspaceIcon'
export { default as StreamAnalyticsJobIcon } from './azure/Microsoft.Analytics/StreamAnalyticsJobIcon'
export { default as SynapseAnalyticsIcon } from './azure/Microsoft.Analytics/SynapseAnalyticsIcon'

export { default as AppPlanIcon } from './azure/Microsoft.Compute/AppPlanIcon'
export { default as AutoManagedVmIcon } from './azure/Microsoft.Compute/AutoManagedVmIcon'
export { default as AvailabilitySetIcon } from './azure/Microsoft.Compute/AvailabilitySetIcon'
export { default as ContainerInstancesIcon } from './azure/Microsoft.Compute/ContainerInstancesIcon'
export { default as DiskIcon } from './azure/Microsoft.Compute/DiskIcon'
export { default as FunctionAppIcon } from './azure/Microsoft.Compute/FunctionAppIcon'
export { default as VirtualMachineIcon } from './azure/Microsoft.Compute/VirtualMachineIcon'
